#!/bin/bash

set -e

# Check whether bundle is built already
echo "Searching for a prebuilt application bundle..."
cd /usr/local/src/meteor/
if [ -f *.tar.gz ]
then
    echo "Archived application bundle is found!"
    tar -xf *.tar.gz --strip 1 -C /opt/meteor/bundle
    exit
fi
if [ -d "bundle" ]
then
    cd ./bundle
    if [ -a "star.json" ]
    then
        echo "Unpacked application bundle is found!"
        mv * /opt/meteor/bundle
        exit
    fi
fi
echo "Prebuilt application bundle not found."

# Locate the ".meteor" folder
cd /usr/local/src/meteor
echo "Searching for application source code..."
METEOR_DIR=$(find ./ -type d -name .meteor -print | head -1)
if [ ! -n "${METEOR_DIR}" ]
then
    echo "Failed to locate application bundle or source code! Please check container configuration."
    exit 1
fi

# Build bundle from the source code
cd ${METEOR_DIR}/..
echo "Building bundle from the source code..."
export NODE_ENV=production
[ -n "$NPM_TOKEN" ] && echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
mkdir -p ~/.ssh
[ -n "$SSH_PRIVATE_KEY" ] && echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
[ -n "$SSH_KNOWN_HOSTS" ] && echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
chmod -R 700 ~/.ssh
meteor npm install
meteor build --directory /opt/meteor
rm -rf /usr/local/src/meteor
echo "Build complete!"
