#!/bin/bash

set -e

# Install NPM dependencies
cd /opt/meteor/bundle/programs/server
echo "Installing NPM dependencies..."
meteor npm install
echo "NPM dependencies installation complete!"

# Remove temp files
rm -rf /tmp/*
