#!/usr/bin/env bash

set -e

# Set environment defaults
: ${METEOR_BUNDLE_FILE:="bundle.tar.gz"}
export METEOR_BUNDLE_FILE

# Check whether bundle is given already
cd /app
echo "Searching for a prebuilt application bundle under the '/app' folder..."
if [ -a "star.json" ]
then
    echo "Unpacked application bundle is found!"
    mv * /opt/meteor/bundle
    exit
fi
if [ -a "${METEOR_BUNDLE_FILE}" ]
then
    echo "Archived application bundle is found!"
    tar xf ${METEOR_BUNDLE_FILE} --strip 1 -C /opt/meteor/bundle
    exit
fi
echo "Prebuilt application bundle not found."

# Locate the ".meteor" folder
cd /usr/local/src
echo "Searching for application source code under the '/usr/local/src' folder..."
METEOR_DIR=$(find ./ -type d -name .meteor -printf '%P\n')
if [ ! -n "${METEOR_DIR}" ]
then
    echo "Failed to locate application bundle or source code! Please check container configuration."
    exit 1
fi

# Build bundle from the source code
cd ${METEOR_DIR}/..
echo "Building bundle from the source code..."
meteor build /opt/meteor --directory
rm -rf /usr/local/src/meteor
echo "Build complete!"

# Install NPM dependencies
cd /opt/meteor/bundle/programs/server
echo "Installing NPM dependencies..."
npm install
echo "NPM dependencies installation complete!"

# Remove temp files
rm -rf /tmp/*